### ISSUE TITLE
Page Reload Error

### ISSUE THREAD

**Issue by fanyinghao** [shincurry/lobe-chat-sync-server#1]
```
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:56
this.#timeoutError = new TimeoutError(opts.message);
^

TimeoutError: Navigation timeout of 30000 ms exceeded
at new Deferred (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:56:34)
at Deferred.create (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:18:16)
at new LifecycleWatcher (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/LifecycleWatcher.js:62:46)
at CdpFrame.waitForNavigation (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:181:29)
at CdpFrame.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)
at CdpPage.waitForNavigation (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:594:43)
at CdpPage.reload (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:686:18)
at Timeout._onTimeout (file:///app/index.js:118:18)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)
```
catch this error. while Page Reload.

I guess it sometime site unavailable such as upgrade.

**Comment by fanyinghao** [comment]
thanks for quick response

**Comment by shincurry** [comment]
sorry, there is a bug, i force pushed again.

```
--- await page.reload({ waitUntil: '' })
+++ await page.reload()
```

c25db5c4ea7303716e17918ee50be643982d9c6d
